### ISSUE TITLE
Probleme beim kompilieren

### ISSUE THREAD

**Issue by capitaenz** [schinken/esp8266-geigercounter#3]
Hallo zusammen,

ich habe Probleme beim kompilieren.
So wie ich verstanden habe ist jetzt die settings.h überflüssig? Wenn ich mir allerdings das Projekt näher ansehe, dann hat es eher den Anschein, dass die wifi.h entfällt...
Welche Datei ich auch auskommentiere, ich bekomme Fehler bei kompilieren.
Um es kurz zu machen, gibt es einen lauffähigen Sketch den ich für mich nur anpassen muss ohne Überraschung?

Danke und VG

**Comment by schinken** [comment]
Wenn du noch sagst, was für eine Fehlermeldung könnte man eventuell helfen. 

>  Um es kurz zu machen, gibt es einen lauffähigen Sketch den ich für mich nur anpassen muss ohne Überraschung?

Sollte dieses Github Repo eigentlich schon sein. Haben schon einige vor dir zum laufen gekriegt ;)

**Comment by capitaenz** [comment]
Moin schinken,

leider geht mir das Ganze nicht so einfach von der Hand und es haben sich Fragen und Probleme bei mir aufgetan:
- Muss ich die settings.h manuell anlegen?
- Die Fehlermeldung, wenn ich die settings.h manuell anlege und auf "Überprüfen" drücke, lautet:

`In file included from C:\Users\mail\Desktop\esp8266-geigercounter-master\esp8266-geigercounter\esp8266-geigercounter.ino:11:0:
settings.h:21:24: error: expected unqualified-id before string constant
 #define MQTT_TOPIC_CPM "sensor/radiation/cpm"
                        ^
C:\Users\mail\Desktop\esp8266-geigercounter-master\esp8266-geigercounter\esp8266-geigercounter.ino:35:6: note: in expansion of macro 'MQTT_TOPIC_CPM'
 char MQTT_TOPIC_CPM[128];
      ^
settings.h:22:24: error: expected unqualified-id before string constant
 #define MQTT_TOPIC_USV "sensor/radiation/uSv"
                        ^
C:\Users\mail\Desktop\esp8266-geigercounter-master\esp8266-geigercounter\esp8266-geigercounter.ino:36:6: note: in expansion of macro 'MQTT_TOPIC_USV'
 char MQTT_TOPIC_USV[128];
      ^
serialCommunication:2:13: error: redefinition of 'const char* delimiter'
 const char* delimiter = ", ";
             ^
In file included from C:\Users\mail\Desktop\esp8266-geigercounter-master\esp8266-geigercounter\esp8266-geigercounter.ino:11:0:
settings.h:26:13: error: 'const char* delimiter' previously defined here
 const char* delimiter = ", ";
             ^
exit status 1
expected unqualified-id before string constant
`

Die Biblioteken mit der richtigen Version habe ich installiert:

    ArduinoJSON 6.10.1
    PubSubClient 2.8.0
    WiFiManager 0.15.0

Ich verwende Arduino IDE 1.8.13

Könnte es am falschen Board in der Auswahl liegen? Ich verwende das WeMos R1 D1.

Danke für deine Hilfe und VG
Leif

**Comment by capitaenz** [comment]
Danke für die angebotene Hilfe @schinken, aber ich habe jetzt eine andere Lösung gefunden.
Wenn jemand anderes eine Lösung sucht, dann bitte mich anschreiben.

PS: Danke für den konstruktiven Daumen nach unten @Hypfer

**Comment by capitaenz** [comment]
@Hypfer 
Es wird der Tag kommen, an dem auch DU, Sören, einmal von wem auch immer, Hilfe benötigst und dann wünsche ich dir trotzdem, dass man dich besser behandelt...
Hoffe dies alles bleibt hier als Spiegel deiner selbst stehen.
