### ISSUE TITLE
Konfiguration des Geigercounters

### ISSUE THREAD

**Issue by Burny4600** [schinken/esp8266-geigercounter#5]
Nach langem habe ich herausgefunden das der Test Wemos D1 Mini defekt war.
Nun wird die Konfiguration ohne Fehler auf den Wemos D1 Mini übertragen.
Jetzt habe ich aber das Problem, wie ich den Wemos D1 Mini erreichen kann. 
In der Datei settings.h habe ich meine WLAN SSID und das WIFI Passwort eingetragen.
Per Ping ist er jedenfalls erreichbar. Hat deine Konfiguration eine Weboberfläche für die weiteren Konfigurationen?
Was ist als Nächstes vorzunehmen?
Hast du eine vollständige Info?

**Comment by schinken** [comment]
> Hat deine Konfiguration eine Weboberfläche für die weiteren Konfigurationen?

nein

> Was ist als Nächstes vorzunehmen?

Sich über MQTT informieren

> Hast du eine vollständige Info?

Sorry, das ichs so sag: Aber ich hab keine Lust jemand ein fertiges Projekt bis ins Detail zu erklären und jemand in sein OpenHAB/HASS/etc zu integrieren. Ein bisschen vorwissen über MQTT/ESP/WLAN/etc... sollte schon vorhanden sein
